PROJECT_NAME="sampleapp"
NEW_PROJECT_NAME=$1
sed -i -e "s/$PROJECT_NAME/$NEW_PROJECT_NAME/g" CMakeLists.txt $PROJECT_NAME.desktop
mv $PROJECT_NAME $NEW_PROJECT_NAME
mv po/$PROJECT_NAME.pot po/$NEW_PROJECT_NAME.pot
mv po/fr/$PROJECT_NAME.po po/fr/$NEW_PROJECT_NAME.po
mv po/fr/$PROJECT_NAME.mo po/fr/$NEW_PROJECT_NAME.mo
